StudentsCRUD/Models/TeacherViewModel/TeacherViewModel.cs
using StudentsCRUD.Entity.Entity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentsCRUD.Models.TeacherViewModel
{
    public class TeacherViewModel : BaseEntity
    {
        [Required(ErrorMessage = "Please enter first name.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter last name.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter email.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter username.")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Please enter password.")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please enter Faculty Qualification Degree.")]
        public string QualificationDegree { get; set; }
    
    }
}

StudentsCRUD/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentsCRUD.Entity.Context;
using StudentsCRUD.Entity.Entity;
using StudentsCRUD.Entity.Repositories;
using StudentsCRUD.Filters;
using StudentsCRUD.Models.TeacherViewModel;

namespace StudentsCRUD.Controllers
{
    public class TeachersController : Controller
    {
        private TeacherRepository repository = new TeacherRepository();

        [AuthenticationFilter(RequireAdminRole = true)]
        public ActionResult Index()
        {
            List<Teacher> teachers = repository.GetAll();

            TeacherListViewModel model = new TeacherListViewModel();
            model.Teachers = teachers;

            return View(model);
        }

        [AuthenticationFilter(RequireAdminRole = true)]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TeacherViewModel teacherViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(teacherViewModel);
            }

            UserRepository userRepository = new UserRepository();
            List<Person> list = userRepository.GetAll();

            if (list.Where(u => u.Email == teacherViewModel.Email).Any())
            {
                ModelState.AddModelError("error_email", "This email is already taken!");
                return View();
            }
            else if (list.Where(u => u.Username == teacherViewModel.Username).Any())
            {

                ModelState.AddModelError("error_username", "This username is already taken!");
                return View();
            }
            else
            {
                Teacher teacher = new Teacher();
                teacher.FirstName = teacherViewModel.FirstName.First().ToString().ToUpper() + String.Join("", teacherViewModel.FirstName.Skip(1));
                teacher.LastName = teacherViewModel.LastName.First().ToString().ToUpper() + String.Join("", teacherViewModel.LastName.Skip(1));
                teacher.QualificationDegree = teacherViewModel.QualificationDegree;
                teacher.Username = teacherViewModel.Username;
                teacher.Password = teacherViewModel.Password;
                teacher.Email = teacherViewModel.Email;

                repository.Insert(teacher);
            }
            return RedirectToAction("Index");
        }

        [AuthenticationFilter(RequireAdminRole = true)]
        public ActionResult Edit(int? id)
        {
            TeacherViewModel model = new TeacherViewModel();

            if (id.HasValue)
            {
                Teacher teacher = repository.GetById(id.Value);
                model.Id = teacher.Id;
                model.FirstName = teacher.FirstName;
                model.LastName = teacher.LastName;
                model.QualificationDegree = teacher.QualificationDegree;
                model.Username = teacher.Username;
                model.Password = teacher.Password;
                model.Email = teacher.Email;
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(TeacherViewModel teacherViewModel)
        {

            Teacher teacher = new Teacher();
            teacher.Id = teacherViewModel.Id;
            teacher.FirstName = teacherViewModel.FirstName.First().ToString().ToUpper() + String.Join("", teacherViewModel.FirstName.Skip(1));
            teacher.LastName = teacherViewModel.LastName.First().ToString().ToUpper() + String.Join("", teacherViewModel.LastName.Skip(1));
            teacher.QualificationDegree = teacherViewModel.QualificationDegree;
            teacher.Username = teacherViewModel.Username;
            teacher.Password = teacherViewModel.Password;
            teacher.Email = teacherViewModel.Email;

            repository.Save(teacher);

            return RedirectToAction("Index");
        }

        [AuthenticationFilter(RequireAdminRole = true)]
        public ActionResult Delete(int id)
        {
            Teacher teacher = repository.GetById(id);

            TeacherViewModel model = new TeacherViewModel();
            model.FirstName = teacher.FirstName;
            model.LastName = teacher.LastName;
            model.QualificationDegree = teacher.QualificationDegree;
            model.Username = teacher.Username;
            model.Password = teacher.Password;
            model.Email = teacher.Email;

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(TeacherViewModel model)
        {
            if (model.Id.ToString() != String.Empty)
            {
                repository.Delete(model.Id);
            }
            return RedirectToAction("Index");
        }
    }
}

StudentsCRUD/Views/Teachers/Create.cshtml
@model StudentsCRUD.Models.TeacherViewModel.TeacherViewModel
@{
    /**/

    ViewBag.Title = "Create";
}

<h2 style="text-align:center">Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, "First Name", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, "Last Name", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control col-md-offset-5" } })
        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QualificationDegree, "Qualification Degree", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

        @{
            List<SelectListItem> listItems = new List<SelectListItem>();
            listItems.Add(new SelectListItem
            {
                Text = "-- Select Degree --",
                Value = "-- Select Degree --",
                Selected = true
            });
            listItems.Add(new SelectListItem
            {
                Text = "Bachelor",
                Value = "Bachelor"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Master",
                Value = "Master",

            });
            listItems.Add(new SelectListItem
            {
                Text = "Doctor",
                Value = "Doctor"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Professor",
                Value = "Professor"
            });

        }

        @Html.DropDownListFor(model => model.QualificationDegree, listItems, new { @class = "form-control col-md-offset" })

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Username, "Username", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control col-md-offset-5" } })
        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
        @Html.ValidationMessage("error_username")
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, "Password", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })
        @Html.PasswordFor(model => model.Password, new { @class = "form-control col-md-offset-5" })
        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, "E-mail", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control col-md-offset-5" } })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        @Html.ValidationMessage("error_email")
    </div>


    <div class="form-group">
        <div class="col-md-offset-5 col-md-10">
            <input type="submit" value="Save" class="btn-success" style="border-radius:15px; background-color:#333; border-color:#333; height:2.5em; width:5em;" />

            <button class="btn-default" style="border-radius:15px; height:2.5em; width:5em;">
                @Html.ActionLink("Cancel", "Index", "Teachers")
            </button>
        </div>
    </div>
</div>
  }

StudentsCRUD/Views/Teachers/Delete.cshtml
@model StudentsCRUD.Models.TeacherViewModel.TeacherViewModel
@{
    ViewBag.Title = "Delete";
}

<h2 style="text-align:center">Delete</h2>

<h4 style="text-align:center;">Are you sure you want to delete this?</h4>

<hr />
<div class="col-md-offset-4">

    <dl class="dl-horizontal">
        <dt style="color: #333; font-size:20px;">
            @Html.DisplayName("First Name")
        </dt>
        <dd style="font-size:20px;">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt style="color: #333; font-size:20px;">
            @Html.DisplayName("Last Name")
        </dt>
        <dd style="font-size:20px;">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt style="color: #333; font-size:20px;">
            @Html.DisplayName("Qualification Degree")
        </dt>
        <dd style="font-size:20px;">
            @Html.DisplayFor(model => model.QualificationDegree)
        </dd>
        <dt style="color: #333; font-size:20px;">
            @Html.DisplayName("Username")
        </dt>
        <dd style="font-size:20px;">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt style="color: #333; font-size:20px;">
            @Html.DisplayName("E-mail")
        </dt>
        <dd style="font-size:20px;">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="col-md-offset-2 col-md-10" style="margin-bottom:30px;">
            <input type="submit" value="Delete" class="btn-success" style="border-radius:15px; background-color:#333; border-color:#333; height:2.5em; width:5em;" />

            <button class="btn-default" style="border-radius:15px; height:2.5em; width:5em;">
                @Html.ActionLink("Cancel", "Index")
            </button>
        </div>
    }
</div>

StudentsCRUD/Views/Teachers/Edit.cshtml
@model StudentsCRUD.Models.TeacherViewModel.TeacherViewModel
@{
    ViewBag.Title = "Edit";
}

<h2 style="text-align:center">Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid">
        <div class="form-horizontal">
            <hr />
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, "First Name", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, "Last Name", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control col-md-offset-5" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.QualificationDegree, "Qualification Degree", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    listItems.Add(new SelectListItem
                    {
                        Text = "-- Select Status --",
                        Value = "-- Select Status --",
                        Selected = true
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Bachelor",
                        Value = "Bachelor"
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Master",
                        Value = "Master",

                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Doctor",
                        Value = "Doctor"
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Professor",
                        Value = "Professor"
                    });

                }

                @Html.DropDownListFor(model => model.QualificationDegree, listItems, new { @class = "form-control col-md-offset" })

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Username, "Username", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control col-md-offset-5" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })

            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.Password, "Password", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })
                @Html.PasswordFor(model => model.Password, new { @class = "form-control col-md-offset-5" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Email, "E-mail", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control col-md-offset-5" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                <div class="col-md-offset-5 col-md-10">
                    <input type="submit" value="Save" class="btn-success" style="border-radius:15px; background-color:#333; border-color:#333; height:2.5em; width:5em;" />

                    <button class="btn-default" style="border-radius:15px; height:2.5em; width:5em;">
                        @Html.ActionLink("Cancel", "Index")
                    </button>
                </div>
            </div>
        </div>
    </div>
}

StudentsCRUD/Views/Teachers/Index.cshtml
@model StudentsCRUD.Models.TeacherViewModel.TeacherListViewModel
@{
    ViewBag.Title = "Index";
}

<h2 style="text-align:center">Teachers</h2>

<button class="btn-success" style="border-radius:25px; background-color:#333; border-color:#333; height:3em; width:7em; margin-bottom:20px; ">
    @Html.ActionLink("Create new", "Create", "Teachers", new { @style = "color:white; text-decoration:none; font-weight:bold;" })
</button>

<table class="table">
    <thead>
        <tr class="btn-success" style="background-color:#333; border-color:#333;">
            <th style="text-align:center;">First Name</th>
            <th style="text-align:center;">Last Name</th>
            <th style="text-align:center;">Qualification Degree</th>
            <th style="text-align:center;">Username</th>
            <th style="text-align:center;">E-mail</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var teacher in Model.Teachers)
        {
        <tr class="bg-info text-white" style="text-align:center; background-color:transparent;">
            <td>@teacher.FirstName</td>
            <td>@teacher.LastName</td>
            <td>@teacher.QualificationDegree</td>
            <td>@teacher.Username</td>
            <td>@teacher.Email</td>
            <td>
                <button class="btn-default" style="border-radius:15px; height:2.5em; width:5em;">
                    @Html.ActionLink("Edit", "Edit", "Teachers", new { id = teacher.Id }, null)
                </button>
                <button class="btn-default" style="border-radius:15px; height:2.5em; width:5em;">
                    @Html.ActionLink("Delete", "Delete", "Teachers", new { id = teacher.Id }, null)
                </button>
            </td>
        </tr>
        }
    </tbody>
</table>