StudentsCRUD/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentsCRUD.Entity.Context;
using StudentsCRUD.Entity.Entity;
using StudentsCRUD.Entity.Repositories;
using StudentsCRUD.Filters;
using StudentsCRUD.Models;

namespace StudentsCRUD.Controllers
{
    public class StudentController : Controller
    {
        private StudentRepository repository = new StudentRepository();


        [AuthenticationFilter(RequireAdminRole = true)]
        public ActionResult Index()
        {
            List<Student> students = repository.GetAll();

            StudentListViewModel model = new StudentListViewModel();
            model.Students = students;

            return View(model);
        }

        [AuthenticationFilter(RequireAdminRole = true)]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(StudentViewModel studentViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(studentViewModel);
            }

            UserRepository userRepository = new UserRepository();
            List<Person> list = userRepository.GetAll();

            if (list.Where(u => u.Email == studentViewModel.Email).Any())
            {
                ModelState.AddModelError("error_email", "This email is already taken!");
                return View();
            }
            else if (list.Where(u => u.Username == studentViewModel.Username).Any())
            {

                ModelState.AddModelError("error_username", "This username is already taken!");
                return View();
            }
            else
            {
                Student student = new Student();
                student.FirstName = studentViewModel.FirstName.First().ToString().ToUpper() + String.Join("", studentViewModel.FirstName.Skip(1));
                student.LastName = studentViewModel.LastName.First().ToString().ToUpper() + String.Join("", studentViewModel.LastName.Skip(1)); ;
                student.Specialty = studentViewModel.Specialty;
                student.FacultyNumber = studentViewModel.FacultyNumber;
                student.Username = studentViewModel.Username;
                student.Password = studentViewModel.Password;
                student.Email = studentViewModel.Email;

                repository.Insert(student);
            }
            return RedirectToAction("Index");
        }

        [AuthenticationFilter(RequireAdminRole = true)]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            StudentViewModel model = new StudentViewModel();

            if (id.HasValue)
            {
                Student student = repository.GetById(id.Value);
                model.Id = student.Id;
                model.FirstName = student.FirstName;
                model.LastName = student.LastName;
                model.Specialty = student.Specialty;
                model.FacultyNumber = student.FacultyNumber;
                model.Username = student.Username;
                model.Password = student.Password;
                model.Email = student.Email;
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(StudentViewModel studentViewModel)
        {

            Student student = new Student();
            student.Id = studentViewModel.Id;
            student.FirstName = studentViewModel.FirstName.First().ToString().ToUpper() + String.Join("", studentViewModel.FirstName.Skip(1));
            student.LastName = studentViewModel.LastName.First().ToString().ToUpper() + String.Join("", studentViewModel.LastName.Skip(1)); ;
            student.Specialty = studentViewModel.Specialty;
            student.FacultyNumber = studentViewModel.FacultyNumber;
            student.Username = studentViewModel.Username;
            student.Password = studentViewModel.Password;
            student.Email = studentViewModel.Email;

            repository.Save(student);

            return RedirectToAction("Index");
        }

        [AuthenticationFilter(RequireAdminRole = true)]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Student student = repository.GetById(id);

            StudentViewModel model = new StudentViewModel();
            model.FirstName = student.FirstName;
            model.LastName = student.LastName;
            model.Specialty = student.Specialty;
            model.FacultyNumber = student.FacultyNumber;
            model.Username = student.Username;
            model.Password = student.Password;
            model.Email = student.Email;

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(StudentViewModel model)
        {
            if (model.Id.ToString() != String.Empty)
            {
                repository.Delete(model.Id);
            }

            return RedirectToAction("Index");
        }

    }
}

StudentsCRUD/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using StudentsCRUD.Entity.Context;
using StudentsCRUD.Entity.Entity;
using StudentsCRUD.Entity.Repositories;
using StudentsCRUD.Filters;
using StudentsCRUD.Models.SubjectViewModel;

namespace StudentsCRUD.Controllers
{
    public class SubjectController : Controller
    {

        
        public ActionResult Index()
        {
            SubjectRepository repository = new SubjectRepository();
            List<Subject> subjects = repository.GetAll();

            SubjectListViewModel model = new SubjectListViewModel();
            model.Subjects = subjects;

            return View(model);
        }

        public ActionResult Create()
        {
            SubjectViewModel model = new SubjectViewModel();
            model.Teachers = PopulateTeacherList();
            model.Title = model.Title;
            model.Description = model.Description;
            model.Credits = model.Credits;
            model.TeacherId = model.TeacherId;

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(SubjectViewModel subjectViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(subjectViewModel);
            }

            Subject subject = new Subject();
            subject.Title = subjectViewModel.Title.First().ToString().ToUpper() + String.Join("", subjectViewModel.Title.Skip(1));
            subject.Description = subjectViewModel.Description.First().ToString().ToUpper() + String.Join("", subjectViewModel.Description.Skip(1));
            subject.TeacherId = subjectViewModel.TeacherId;
            subject.Credits = subjectViewModel.Credits;

            var repository = new SubjectRepository();
            repository.Insert(subject);

            return RedirectToAction("Index");
        }

        private List<SelectListItem> PopulateTeacherList()
        {
            List<SelectListItem> result = new List<SelectListItem>();
            TeacherRepository teacherRepository = new TeacherRepository();
            List<Teacher> teachers = teacherRepository.GetAll();
            foreach (Teacher teacher in teachers)
            {
                SelectListItem item = new SelectListItem();
                item.Value = teacher.Id.ToString();
                item.Text = $"{teacher.FirstName} {teacher.LastName }";

                result.Add(item);
            }

            return result;
        }

        public ActionResult Edit(int? id)
        {
            SubjectRepository repository = new SubjectRepository();
            SubjectViewModel model = new SubjectViewModel();

            if (id.HasValue)
            {
                Subject subject = repository.GetById(id.Value);
                model.Id = subject.Id;
                model.Title = subject.Title;
                model.Description = subject.Description;
                model.Credits = subject.Credits;
                model.Teachers = PopulateTeacherList();
                model.TeacherId = subject.TeacherId;
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(SubjectViewModel subjectViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(subjectViewModel);
            }

            SubjectRepository repository = new SubjectRepository();

            Subject subject = new Subject();
            subject.Id = subjectViewModel.Id;
            subject.Title = subjectViewModel.Title.First().ToString().ToUpper() + String.Join("", subjectViewModel.Title.Skip(1));
            subject.Description = subjectViewModel.Description.First().ToString().ToUpper() + String.Join("", subjectViewModel.Description.Skip(1));
            subject.Credits = subjectViewModel.Credits;
            subject.TeacherId = subjectViewModel.TeacherId;

            repository.Save(subject);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            SubjectRepository repository = new SubjectRepository();
            Subject subject = repository.GetById(id);

            SubjectViewModel model = new SubjectViewModel();
            model.Title = subject.Title;
            model.Description = subject.Description;
            model.Credits = subject.Credits;
            model.TeacherId = subject.TeacherId;

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(SubjectViewModel subjectViewModel)
        {
            SubjectRepository repository = new SubjectRepository();
            if (subjectViewModel.Id.ToString() != String.Empty)
            {
                repository.Delete(subjectViewModel.Id);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ShowTeacherSubjects()
        {
            int userId = LoginFilter.GetUserId();
            SubjectRepository repository = new SubjectRepository();
            List<Subject> subjects = repository.GetAll();

            List<Subject> teacherSubjects = new List<Subject>();

            foreach (var subject in subjects)
            {
                if (subject.TeacherId == userId)
                {
                    teacherSubjects.Add(subject);
                }
                else
                {
                    ViewBag.Message = "This user has no subjects yet!";
                }
            }

            SubjectListViewModel model = new SubjectListViewModel();
            model.Subjects = teacherSubjects;

            return View(model);
        }
    }
}

StudentsCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        footer {
            position: absolute;
            bottom: 0;
            left: 40%;
        }

          h2 {
               font-family:Oregano;
               font-size:4em;
            }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("University System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" , @style= "font-family:Oregano;font-size:2em;" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @{
                        if (StudentsCRUD.Filters.LoginFilter.IsNotLogedUser() == false)
                        {
                            if (StudentsCRUD.Filters.LoginFilter.GetRole() == (int)StudentsCRUD.Filters.Enums.UserRoles.Admin)
                            {
                                <li>@Html.ActionLink("Students", "Index", "Student")</li>
                                <li>@Html.ActionLink("Teachers", "Index", "Teachers")</li>
                                <li>@Html.ActionLink("Admins", "Index", "Admins")</li>

                                <li>@Html.ActionLink("Subjects", "Index", "Subject")</li>
                                <li class="btn-default">@Html.ActionLink("Logout", "Logout", "Home")</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("Subjects", "Index", "Subject")</li>
                                <li class="btn-default">@Html.ActionLink("Logout", "Logout", "Home")</li>
                            }

                        }
                        else
                        {

                            <li>@Html.ActionLink("Login", "Login", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        }
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <footer>
            <p>&copy; @DateTime.Now.Year - University System By Madlen Stoicheva</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>