StudentsCRUD/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentsCRUD.Entity.Context;
using StudentsCRUD.Entity.Entity;
using StudentsCRUD.Entity.Repositories;
using StudentsCRUD.Filters;
using StudentsCRUD.Filters.Enums;
using StudentsCRUD.Models.AdminViewModel;

namespace StudentsCRUD.Controllers
{
    public class AdminsController : Controller
    {

        private AdminRepository repository = new AdminRepository();

        [AuthenticationFilter(RequireAdminRole = true)]
        public ActionResult Index()
        {
            List<Admin> admins = repository.GetAll();

            AdminListViewModel model = new AdminListViewModel();
            model.Admins = admins;

            return View(model);
        }

        [AuthenticationFilter(RequireAdminRole = true)]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create( AdminViewModel adminViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(adminViewModel);
            }

            UserRepository userRepository = new UserRepository();
            List<Person> list = userRepository.GetAll();

            if (list.Where(u => u.Email == adminViewModel.Email).Any())
            {
                ModelState.AddModelError("error_email", "This email is already taken!");
                return View();
            }
            else if (list.Where(u => u.Username == adminViewModel.Username).Any())
            {

                ModelState.AddModelError("error_username", "This username is already taken!");
                return View();
            }
            else
            {
                Admin admin = new Admin();
                admin.FirstName = adminViewModel.FirstName.First().ToString().ToUpper() + String.Join("", adminViewModel.FirstName.Skip(1));
                admin.LastName = adminViewModel.LastName.First().ToString().ToUpper() + String.Join("", adminViewModel.LastName.Skip(1));
                admin.Email = adminViewModel.Email;
                admin.Username = adminViewModel.Username;
                admin.Password = adminViewModel.Password;

                repository.Insert(admin);
            }
            
            return RedirectToAction("Index");
        }

        [AuthenticationFilter(RequireAdminRole = true)]
        public ActionResult Edit(int? id)
        {
            AdminViewModel model = new AdminViewModel();

            if (id.HasValue)
            {
                Admin admin = repository.GetById(id.Value);
                model.Id = admin.Id;
                model.FirstName = admin.FirstName;
                model.LastName = admin.LastName;
                model.Email = admin.Email;
                model.Username = admin.Username;
                model.Password = admin.Password;
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(AdminViewModel adminViewModel)
        {

            Admin admin = new Admin();
            admin.Id = adminViewModel.Id;
            admin.FirstName = adminViewModel.FirstName.First().ToString().ToUpper() + String.Join("", adminViewModel.FirstName.Skip(1));
            admin.LastName = adminViewModel.LastName.First().ToString().ToUpper() + String.Join("", adminViewModel.LastName.Skip(1));
            admin.Username = adminViewModel.Username;
            admin.Password = adminViewModel.Password;
            admin.Email = adminViewModel.Email;

            repository.Save(admin);

            return RedirectToAction("Index");
        }

        [AuthenticationFilter(RequireAdminRole = true)]
        public ActionResult Delete(int id)
        {
            Admin admin = repository.GetById(id);

            AdminViewModel model = new AdminViewModel();
            model.FirstName = admin.FirstName;
            model.LastName = admin.LastName;
            model.Username = admin.Username;
            model.Password = admin.Password;
            model.Email = admin.Email;

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(AdminViewModel model)
        {
            if (model.Id.ToString() != String.Empty)
            {
                repository.Delete(model.Id);
            }
            return RedirectToAction("Index");
        }

    }
}

StudentsCRUD/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentsCRUD.Entity.Context;
using StudentsCRUD.Entity.Entity;
using StudentsCRUD.Entity.Repositories;
using StudentsCRUD.Filters;
using StudentsCRUD.Models;

namespace StudentsCRUD.Controllers
{
    public class StudentController : Controller
    {
        private StudentRepository repository = new StudentRepository();


        [AuthenticationFilter(RequireAdminRole = true)]
        public ActionResult Index()
        {
            List<Student> students = repository.GetAll();

            StudentListViewModel model = new StudentListViewModel();
            model.Students = students;

            return View(model);
        }

        [AuthenticationFilter(RequireAdminRole = true)]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(StudentViewModel studentViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(studentViewModel);
            }

            UserRepository userRepository = new UserRepository();
            List<Person> list = userRepository.GetAll();

            if (list.Where(u => u.Email == studentViewModel.Email).Any())
            {
                ModelState.AddModelError("error_email", "This email is already taken!");
                return View();
            }
            else if (list.Where(u => u.Username == studentViewModel.Username).Any())
            {

                ModelState.AddModelError("error_username", "This username is already taken!");
                return View();
            }
            else
            {
                Student student = new Student();
                student.FirstName = studentViewModel.FirstName.First().ToString().ToUpper() + String.Join("", studentViewModel.FirstName.Skip(1));
                student.LastName = studentViewModel.LastName.First().ToString().ToUpper() + String.Join("", studentViewModel.LastName.Skip(1)); ;
                student.Specialty = studentViewModel.Specialty;
                student.FacultyNumber = studentViewModel.FacultyNumber;
                student.Username = studentViewModel.Username;
                student.Password = studentViewModel.Password;
                student.Email = studentViewModel.Email;

                repository.Insert(student);
            }
            return RedirectToAction("Index");
        }

        [AuthenticationFilter(RequireAdminRole = true)]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            StudentViewModel model = new StudentViewModel();

            if (id.HasValue)
            {
                Student student = repository.GetById(id.Value);
                model.Id = student.Id;
                model.FirstName = student.FirstName;
                model.LastName = student.LastName;
                model.Specialty = student.Specialty;
                model.FacultyNumber = student.FacultyNumber;
                model.Username = student.Username;
                model.Password = student.Password;
                model.Email = student.Email;
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(StudentViewModel studentViewModel)
        {

            Student student = new Student();
            student.Id = studentViewModel.Id;
            student.FirstName = studentViewModel.FirstName.First().ToString().ToUpper() + String.Join("", studentViewModel.FirstName.Skip(1));
            student.LastName = studentViewModel.LastName.First().ToString().ToUpper() + String.Join("", studentViewModel.LastName.Skip(1)); ;
            student.Specialty = studentViewModel.Specialty;
            student.FacultyNumber = studentViewModel.FacultyNumber;
            student.Username = studentViewModel.Username;
            student.Password = studentViewModel.Password;
            student.Email = studentViewModel.Email;

            repository.Save(student);

            return RedirectToAction("Index");
        }

        [AuthenticationFilter(RequireAdminRole = true)]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Student student = repository.GetById(id);

            StudentViewModel model = new StudentViewModel();
            model.FirstName = student.FirstName;
            model.LastName = student.LastName;
            model.Specialty = student.Specialty;
            model.FacultyNumber = student.FacultyNumber;
            model.Username = student.Username;
            model.Password = student.Password;
            model.Email = student.Email;

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(StudentViewModel model)
        {
            if (model.Id.ToString() != String.Empty)
            {
                repository.Delete(model.Id);
            }

            return RedirectToAction("Index");
        }

    }
}

StudentsCRUD/Views/Admins/Create.cshtml
@model StudentsCRUD.Models.AdminViewModel.AdminViewModel
@{
    /**/

    ViewBag.Title = "Create";
}

<h2 style="text-align:center;">Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, "First Name", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, "Last Name", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control col-md-offset-5" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, "Username", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control col-md-offset-5" } })
            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            @Html.ValidationMessage("error_username")
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, "Password", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })
            @Html.PasswordFor(model => model.Password, new { @class = "form-control col-md-offset-5" })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, "E-mail", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control col-md-offset-5" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            @Html.ValidationMessage("error_email")
        </div>

        <div class="form-group">
            <div class="col-md-offset-5 col-md-10">
                <input type="submit" value="Save" class="btn-success" style="border-radius:15px; background-color:#333; border-color:#333; height:2.5em; width:5em;" />

                <button class="btn-default" style="border-radius:15px; height:2.5em; width:5em;">
                    @Html.ActionLink("Cancel", "Index", "Student")
                </button>
            </div>
        </div>
    </div>

}

StudentsCRUD/Views/Admins/Delete.cshtml
@model StudentsCRUD.Models.AdminViewModel.AdminViewModel
@{
    ViewBag.Title = "Delete";
}

<h2 style="text-align:center;">Delete</h2>

<h4 style="text-align:center;">Are you sure you want to delete this?</h4>

<hr />
<div class="col-md-offset-4">

    <dl class="dl-horizontal">
        <dt style="color: #333; font-size:20px;">
            @Html.DisplayName("First Name")
        </dt>
        <dd style="font-size:20px;">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt style="color: #333; font-size:20px;">
            @Html.DisplayName("Last Name")
        </dt>
        <dd style="font-size:20px;">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt style="color: #333; font-size:20px;">
            @Html.DisplayName("Username")
        </dt>
        <dd style="font-size:20px;">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt style="color: #333; font-size:20px;">
            @Html.DisplayName("E-mail")
        </dt>
        <dd style="font-size:20px;">
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="col-md-offset-2 col-md-10" style="margin-bottom:30px;">
            <input type="submit" value="Delete" class="btn-success" style="border-radius:15px; background-color:#333; border-color:#333; height:2.5em; width:5em;" />

            <button class="btn-default" style="border-radius:15px; height:2.5em; width:5em;">
                @Html.ActionLink("Cancel", "Index")
            </button>
        </div>
    }
</div>

StudentsCRUD/Views/Admins/Edit.cshtml
@model StudentsCRUD.Models.AdminViewModel.AdminViewModel
@{
    ViewBag.Title = "Edit";
}

<h2 style="text-align:center;">Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, "First Name", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, "Last Name", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control col-md-offset-5" } })
        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Username, "Username", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control col-md-offset-5" } })
        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })

    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.Password, "Password", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })
            @Html.PasswordFor(model => model.Password, new { @class = "form-control col-md-offset-5" })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Email, "E-mail", htmlAttributes: new { @class = "control-label col-md-5", @style = "color: #333; font-size:22px;" })

        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control col-md-offset-5" } })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

    </div>

    <div class="form-group">
        <div class="col-md-offset-5 col-md-10">
            <input type="submit" value="Save" class="btn-success" style="border-radius:15px; background-color:#333; border-color:#333; height:2.5em; width:5em;" />

            <button class="btn-default" style="border-radius:15px; height:2.5em; width:5em;">
                @Html.ActionLink("Cancel", "Index")
            </button>
        </div>
    </div>
</div>
}

StudentsCRUD/Views/Admins/Index.cshtml
@model StudentsCRUD.Models.AdminViewModel.AdminListViewModel
@{
    /**/
    ViewBag.Title = "Index";
}

<h2 style="text-align:center">Admins</h2>

<button class="btn-success" style="border-radius:25px; background-color:#333; border-color:#333; height:3em; width:7em; margin-bottom:20px; ">
    @Html.ActionLink("Add new", "Create", "Admins", new { @style = "color:white; text-decoration:none; font-weight:bold;" })
</button>

<table class="table">
    <thead>
        <tr class="btn-success" style="background-color:#333; border-color:#333;">
            <th style="text-align:center;">First Name</th>
            <th style="text-align:center;">Last Name</th>
            <th style="text-align:center;">Username</th>
            <th style="text-align:center;">E-mail</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var admins in Model.Admins)
        {
            <tr class="bg-info text-white" style="text-align:center; background-color:transparent;">
                <td>@admins.FirstName</td>
                <td>@admins.LastName</td>
                <td>@admins.Username</td>
                <td>@admins.Email</td>
                <td>
                    <button class="btn-default" style="border-radius:15px; height:2.5em; width:5em;">
                        @Html.ActionLink("Edit", "Edit", "Admins", new { id = admins.Id }, null)
                    </button>
                    <button class="btn-default" style="border-radius:15px; height:2.5em; width:5em;">
                        @Html.ActionLink("Delete", "Delete", "Admins", new { id = admins.Id }, null)
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>